set -g status-position bottom
set -g status-interval 1
set -g status-style "bg=#11111b,fg=#cdd6f4"
set -g message-style "bg=#1e1e2e,fg=#cdd6f4"

set -g pane-border-lines single
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#89dceb"

set -g window-style "dim"
set -g window-active-style "nodim"

set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[fg=#11111b,bg=#cba6f7,bold] #S "
set -g status-right "#[fg=#f5e0dc,bg=#11111b] %Y-%m-%d %H:%M "

set -g window-status-format "#[fg=#cdd6f4,bg=#181825] #I:#W "
set -g window-status-current-format "#[fg=#11111b,bg=#cba6f7,bold] #I:#W "
