set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'omerxx/tmux-sessionx'

set -g @sessionx-bind 'w'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-layout 'reverse'
set -g @sessionx-bind-kill-session 'ctrl-k'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-filter-mru 'false'

set -g @resurrect-dir '~/.local/state/tmux/resurrect'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'
