# ==========================================
# 插件管理 (Plugins)
# ==========================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'omerxx/tmux-sessionx'

# Sessionx 入口键（prefix + w）
set -g @sessionx-bind 'w'

# 浮窗 UI 美化设置 (完美适配你的极客屏)
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-layout 'reverse'
set -g @sessionx-bind-kill-session 'ctrl-k'

# 开启 Zoxide 智能目录跳转支持 (输入目录名直接创建/跳转 Session)
set -g @sessionx-zoxide-mode 'on'

# 自定义一些按键行为 (在浮窗内按 ? 可查看所有快捷键)
set -g @sessionx-filter-mru 'false'

# 插件专属配置（需在 TPM run 之前）
set -g @resurrect-dir '~/dotfiles/tmux/resurrect'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'
