# ==========================================
# Tmux 主配置 (仅负责加载模块)
# ==========================================
source-file /Users/shawn/dotfiles/tmux/conf.d/00-prefix.conf
source-file /Users/shawn/dotfiles/tmux/conf.d/10-core.conf
source-file /Users/shawn/dotfiles/tmux/conf.d/20-keybindings.conf
source-file /Users/shawn/dotfiles/tmux/conf.d/30-ui.conf
source-file /Users/shawn/dotfiles/tmux/conf.d/40-plugins.conf

# 初始化 TPM 插件管理器 (必须放在文件绝对末尾!)
run '~/.tmux/plugins/tpm/tpm'
