# ---------------------------------------------------------
# 🧩 Tmux 宏快捷键 (Tmux Macros)
# ---------------------------------------------------------
# 当前 tmux prefix = Ctrl-a
# Ctrl-a z: 最大化/恢复 pane
keybind = ctrl+shift+z=text:\x01z

# Ctrl-a H/L: 前一个/后一个窗口
keybind = cmd+shift+bracket_left=text:\x01H
keybind = cmd+shift+bracket_right=text:\x01L
